== 05. Configuring your Development system

=== Setting up system packages

Install the following packages: `build-essential`, `vim`, `git`, `cscope`, `libncurses-dev`, `libssl-dev`, `bison`, `flex`, and `git-email`.


=== Setting up `git email`

To configuring `git email` to send patches:
----
git config sendemail.smtpserver <url>
git config sendemail.smtpserverport <port_nb>
git config sendemail.smtpencryption <encryption_type>
git config sendemail.smtpuser <username>
git config sendemail.smtppass <password>
----
Few common values are:

* `<url>`: smtp.gmail.com
* `<port_nb>`: 587
* `<encryption_type>`: tls

To send patch via email:
----
git send-email <patch_file>
----
[CAUTION]
====
If you have enabled 2-factor authentication on your email account, you may see a failure:

----
ERROR: STARTTLS failed! SSL connect attempt failed error:1416F086:SSL
----

Whenever 2-factor authentication is enabled, you'll need to generate an app specific password for authentication.
Hence, to generate a password for using git, you can refer to *EXAMPLES* section https://git-scm.com/docs/git-send-email[here].
====


[IMPORTANT]
====
Instead of git, if you are using your email client to send the patches, make sure that in your mailing process to:

* Turn off html encoding and send plain ASCII text
* Turn off any line-wrapping or flowing
* Send your patch directly in the email message instead of as an attachment
* Don't write your signature or any other personal information
====

=== Setting up email client

Even if you use `git` to send patches, you'll still have to configure your email client to communicate with community.

Configuring email client:

* Disable HTML format, don't use it for any communication
+
[CAUTION]
====
Messages with html in it are automatically discarded
====
* Disable signature
* Never write your message above the original text while responding to an email.
Always write it at the bottom of the original text, in other words configure your client to 'bottom post'.


[IMPORTANT]
====

* Other than sharing kernel logs, and configuration files while reporting bugs, don't send any attachments in any communications.

* Follow inline posting i.e. when reviewing or responding to a patch, delete the parts of the message that you are not replying to.
====
