== Chapter 4: Using Git
You can think of the whole version control system having 3 parts:

* local folder(your project folder)
* local repository(`.git` folder at the root of your project folder)
* remote repository(your repository on GitHub, GitLab etc.)

The workflow is:

* work on the local folder
* stage the changes(`git add`, `git rm`, `git mv`)
* update the changes to the local repository(`git commit`)
* sync local repository to remote repository(`git push`)

=== Commands

==== Local repo

All the commands described in this section is not aware of(and do not even require) the existence of a remote repository.
Hence, network connection is not required.

===== Setting up repo
* Initializing a repository:
+
----
git init
----

* To configure repository author:
+
----
git config user.name "<name>"
git config user.email "<email>"
----
+
This needs to be done for each project unless you have a global configuration file

* To clone a remote repository:
+
----
git clone <url>
----
+
The `<url>` ends with `.git`.
To save space wherever possible, git will use hard links, to prevent this use `--no-hardlinks`.

===== Staging changes
* To add a file from the folder to the repository or update changes from the file on the folder to the repository:
+
----
git add <file>
----

* To remove a file from repository:
+
----
git rm <file>
----
+
[NOTE]
====
If you delete a file from folder first via `rm`, then the file still exists in the repository.
So, you'll need to do `git rm`.

If you don't delete the file from folder via `rm` but simply, execute `git rm`, then in one go the file gets deleted from both the folder and the repository.
====

* To move/rename a file in repository:
+
----
git mv <src_file> <dst_file>
----
+
[NOTE]
====
If you move/rename a file in folder via `mv`, then you've not moved/renamed the file in the repository.
Hence, looking at the changes, git will think you deleted a file from folder and added a file to the folder.
Hence, you'll need to do:

----
git rm <old_file>
git add <new_file>
----

If you don't move/rename the file in folder via `mv` but simply, execute `git mv`, then in one go the file gets moved/renamed in both the folder and the repository.
====

===== Committing changes
* To see the list of changes:
+
----
git diff <commit_id_1> <commit_id_2> <file_directory>
----
+
This shows all the changes in `<file_directory>`, between two commits on the repository.
Dropping `<file_directory>` will compare the whole project.
Dropping `<commit_id_2>`, will compare current branch with `<commit_id_1>`.
Dropping both `<commit_id_1>` and `<commit_id_2>`, will compare between the changes un-staged in the folder copy and the last staged or committed changes on the current branch on the repository.
Therefore, in this case, after staging your changes, there is no diff until you modify the file again unless you use option `--cached`.
+
Additionally, `--ignore-all-space` will ignore whitespaces, `--stat` or `--numstat` will generate a short summary of statistics instead of long output.
+
[NOTE]
====
`git diff` output is already in the patch format, so to create a patch:

----
<git_diff_cmd> > <patch_file>
----
====

* To save the changes to the repository:
+
----
git commit -m "<commit_msg>" <file>
----
+
Giving argument `<file>` will save changes to a specific file, but dropping the argument altogether will save all the changes.
Option `s` can be used to sign-off commit
+
[WARNING]
====
If you don't provide `<commit_msg>`, an editor defined in `EDITOR` or `GIT_EDITOR` environment variable will open, wherein you can type your commit message.
If you don't, commit will fail.
====

* To assign tag to a commit for easy identification:
+
----
git tag <tag_name> <commit_string>
----
+
[TIP]
====
In any git command, whenever commit string is required, you need not write the whole 40 character string.
You can just enter the beginning part enough to uniquely distinguish it from other commit strings.
====
+
[WARNING]
====
Although possible, it is very painful to rename tags.
So, think of it as immutable.
====

* To see the diff between a commit and its previous commit:
+
----
git log -p <commit_name>
----
+
The `<commit_name>` can be:

** commit string of a specific commit
** the tag associated with the commit
** empty or `HEAD` both means the most recent commit
** `HEAD~` refers to parent of `HEAD`(a commit before `HEAD`)
** `HEAD~~` or `HEAD~2` referring to the grandparent of `HEAD`

* To get code from a commit:
+
----
git checkout <commit_name> <file_name>
----
+
If you drop `<file_name>`, whole project is obtained.
+
[NOTE]
====
Untracked files are not deleted when you check out.
====

* To revert a commit:
** If the changes have been published
+
----
git revert <commit_name>
----
+
It creates a new commit whose change-set is the changes required to take repository from current state to the `<commit_name>` commit.
After all the changes have been published, all the history is immutable.
Hence, as we revert to old state, we cannot just delete redundant commits.
So, a new commit is created.

** If the changes have not been published
+
----
git reset <option> <commit_name>
----
+
Since, changes are not yet published, you can still modify history.
Hence, in this case you can remove commits.
+
`<option>` can be:
+
|====
|Option |Commit records post reset commit |Staged changes |Project files |`git diff` behavior

|`--soft`
|Deleted
|Not deleted
|Not reverted
|Here, as files are not reverted and staged info is not reverted, changes in the project file are already staged.
Therefore, nothing for `git diff` to compare.

|`--mixed` (default)
|Deleted
|Deleted (meaning there is nothing staged i.e. `git diff` compares project files with commit)
|Not reverted
|Here, as files are not reverted and staged info is reverted, changes in the project file are yet to be staged.
Therefore, there is something for `git diff` to compare.

|`--hard`
|Deleted
|Deleted
|Reverted
|Here, as files are reverted and staged info is reverted, there is nothing to stage.
Therefore, there is something for `git diff` to compare.
|====
+
[CAUTION]
====
Even `--hard` will not actually delete the untracked files.
You'll need to do:

----
git clean -fdx
----
to delete untracked, and ignored files, and directories
====
* Bisection:
+
Given the bug in current commit, if you know the commit where there was no bug, you can find and revert to the commit that introduced the bug using binary search.

** Search
*** If your current commit has the bug
+
----
git bisect start
git bisect bad
git bisect good <commit_nb_with_no_bug>
----
+
this will check out the code of a commit midway current commit with the bug and the last know good commit

*** After testing your code:
**** If your code still has the bug
+
----
git bisect bad
----
**** If your code does not have the bug
+
----
git bisect good
----

*** When you have finally found the commit that introduced your bug, you can end bisection:
+
----
git bisect reset
----


** Track bisection history(before it `reset` is executed)
*** To log
+
----
git bisect log
----
*** To visualize
+
----
git bisect visualize
----

===== Branching
* To create a branch:
+
----
git branch <branch_name> <starting_point>
----
+
`<branch_name>` must not have any blank spaces, control characters, special characters or slashes at the end.
If you drop `<starting_point>`, a branch will be created off of the active branch.

* To delete to a branch:
+
----
git branch -d <branch_name>
----

* To switch to a branch:
+
----
git checkout <branch_name>
----
+
[IMPORTANT]
====
If you have un-committed changes, git won't let you switching to a new branch
====

* To view detailed info about branches
+
----
git show-branch
----

* To view the list of branches:
+
----
git branch -a
----
+
The active one will be starred.
The remote ones, if exists, will be marked in remote color.

===== Merging
[CAUTION]
====
Before merging:

* Commit or discard any uncommitted changes
* clean:
+
----
git gc
----
* check for existing conflicts:
+
----
git status
----
====

To merge 2 branches:
----
git merge <branch_name>
----
`<branch_name>` is the name of the branch that needs to be merged into the current branch.

Wherever there is no conflict, changes are merged.
Wherever there are conflicts, for every file which has a conflict, 2 sets of files are produced.
Hence, in total we will see 3 files in the folder with the same name:

* File from current branch
* File from `<branch_name>` branch
* File with diff of current branch and `<branch_name>` branch

[IMPORTANT]
====
All the 3 set are visible only when you do:

----
git ls-files
----
not with regular `ls`.
====

[CAUTION]
====
The file shown in the output of `ls` is the 3rd file.
In other words, file in current branch is replaced with diff file.
====

To resolve conflict you can choose either of the approach:

* Rework and retry
** Cancel the merge on the current branch:
+
----
git reset --hard <current_branch_name>
----
** Work on both current branch and `<branch_name>` in such a way that a merge will not lead to any conflict
** Retry merge

* Use the diff file
** Review the conflict locations and choose either one of them and delete the other
** then commit your changes.

[NOTE]
====
Now you should see one 1 file with `git ls-files`
====

* To rebase a branch:
+
----
git rebase <parent_branch> <child_branch>
----
+
All commits since the branching point is removed, and saved in `.git/rebase-apply`.
The `<child_branch>` is moved forward to the latest version of `<parent_branch>`, and then each of the changes is applied to the `<child_branch>`.
+
Any conflicts arising will need to be handled in the same fashion as merge i.e. Resolve issues manually and stage the files.
+
But, after fixing conflicts, unlike merge where you did `git commit`, here you do:
+
----
git rebase --continue
----
+
If something went wrong, and you'd like to cancel:
+
----
git rebase --abort
----


===== Examining the repo
* To see the current status of project:
+
----
git status
----
+
This shows summary of all the changes on the project folder in comparison to the last commit on the current branch on the repository.

* To see the history of project:
+
----
git log
----

* To get just the commit headings:
+
----
git log | grep "^commit"
----
+
or, for one line summary:
+
----
git log --pretty=oneline
----

* To see the list of files in the repository:
+
----
git ls-files
----
+
using `--others` will show all the untracked files(including ignored), `--exclude-standard` will not show ignored files while showing untracked files.

* To see who made a particular change in a file:
+
----
git blame <options> <file>
----
+
Dropping `<options>` will show the developer(s) responsible for all the lines in the file.
With `-L <start>,<end>` as `<options>` you can see the developer responsible for the line numbers `<start>` to `<end>`.

* To see a particular version of the file:
+
----
git show <commit_id>:<file_name>
----

* To list all tags:
** To list just available tags
+
----
git tag
----
** To list tags and the corresponding commit strings:
+
----
git show-ref
----

==== Remote repo
All the commands described in this section works with a remote repository in one form or another.
The remote repository may reside on your local machine or on the web in which case you'll need a network connection.

===== Setting up repo
* To clone a remote repository:
+
----
git clone <url> <dst_dir>
----
+
Dropping `<dst_dir>` will clone into pwd.
The `<url>` normally ends with `.git`.
To save space wherever possible, git will use hard links, to prevent this use `--no-hardlinks`.

* To update local repository with changes from the remote one:
+
----
git pull
----

===== Syncing
* To update your local repository metadata from remote:
+
----
git fetch
----

* To update the current branch on the local repository with a branch on the remote repository:
+
----
git merge origin/<remote_branch>
----

* To update your local repository with all metadata from remote repository and update the current branch on the local repository with a branch on the remote repository:
+
----
git pull origin <remote_branch>
----
+
this is equivalent to:
+
----
git fetch
git merge origin/<remote_branch>
----

* To update the branch of a remote repository with the changes from a branch of your local repository:
+
----
git push <url> <branch_name>
----
+
If you drop `<branch_name>`, everything gets synced.
+
[WARNING]
====
The remote repository should be a bare repository not a development one.
====

===== Examining the repo
* To list tags and corresponding commit strings:
+
----
git ls-remote <url>
----

==== Misc
* To get version of current installation:
+
----
git --version
----

* To tidy the repo:
+
----
git gc
----

* To check repo for errors:
+
----
git fsck
----

* To remove dangling objects:
+
----
git prune
----
+
Option `n` can be used to do a dry run first to see what might be removed.

* To archive just the project files(without the repository i.e. `.git` folder):
+
----
git archive --verbose <commit_id> | bzip2 > <archive_name>.tar.bz2
----
+
dropping `<commit_id>` will cause the current branch's latest commit as the input.

===== Patch

* To create a patch:
+
----
git format-patch -s -<n>
----
+
`<n>` is a number, and it will create patch file for last `n` commits with names like: `<n>-<nth_commit_msg>.patch`
+
Dropping it will create only one patch file for the last commit.
Providing `<branch_name>` argument will create patch between current branch and the `<branch_name>`.
+
You can use `<commit_id>` as argument as well to produce patch between last commit and the particular `<commit_id>` commit.

* To send a patch by email:
+
----
git send-email -to <email_id> <patch_file>
----

* Preview applying a patch:
+
----
git apply --check --cached <patch_file>
----
+
`--cached` will preview applying changes to index as well.
It is recommended to do this before using `git am`.
If you drop the `--check`, you'll apply the patch.

* Applying patch and commit:
** To apply a patch
+
----
git am <patch_file>
----
+
if any conflicts exist, patching will fail, and conflicts have to be resolved one by one.
** After conflict resolution:
+
----
git am --resolved
----
** To back off the conflict resolution and simply restore the original branch:
+
----
git am --abort
----

==== Help
* To get help:
+
----
git help
----

* To see the list of all commands:
+
----
git help --all
----
+
[NOTE]
====
In most cases we just use a handful of them.
No need to be intimidated by the long list.
====

* To get help for a particular command:
+
----
git help <command>
----
